steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/krafs:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/krafs:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "krafs"
      - "--image"
      - "gcr.io/$PROJECT_ID/krafs:$COMMIT_SHA"
      - "--region"
      - "asia-southeast2"
images:
  - "gcr.io/$PROJECT_ID/krafs:$COMMIT_SHA"
options:
  logging: LEGACY

timeout: "1200s"
logsBucket: "gs://krafs-logsbucket"
serviceAccount: "forbuild@krafs-405409.iam.gserviceaccount.com"
